<?php
namespace JianHan\GooglePlaces;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-06 at 07:19:19.
 */
class PlaceAdapterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PlaceAdapter
     */
    protected $textSearchPlaceAdapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->textSearchPlaceAdapter = new PlaceAdapter(AbstractPlace::getInstance('TextSearch', 'validKey'), new \GuzzleHttp\Client());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->textSearchPlaceAdapter = NULL;
    }

    public function validResponseFormat()
    {

        return [

            ['json'], ['xml']

        ];

    }

    /**
     * @covers JianHan\GooglePlaces\PlaceAdapter::request
     */
    public function testRequest()
    {
        // $this->textSearchPlaceAdapter->request([]);
    }

    /**
     * @covers JianHan\GooglePlaces\PlaceAdapter::autoGenerateRequestUrl
     * @covers JianHan\GooglePlaces\PlaceAdapter::getRequestUrl
     * @dataProvider validResponseFormat
     */
    public function testAutoGenerateRequestUrl_AutoGenerateRequestUrl_Success($responseFormat)
    {

        $this->textSearchPlaceAdapter->request(['query' => 'test'], $responseFormat);

        $this->assertEquals($this->textSearchPlaceAdapter->getRequestUrl(), Adapter::API_BASE_URL.'textsearch/'.$responseFormat);

    }

    /**
     * @covers JianHan\GooglePlaces\PlaceAdapter::getPlace
     * @covers JianHan\GooglePlaces\PlaceAdapter::request
     * @dataProvider validResponseFormat
     */
    public function testAutoGenerateRequestUrl_AssignRequestParameters_Success($responseFormat)
    {

        $requestParameters = ['query' => 'test'];

        $this->textSearchPlaceAdapter->request($requestParameters, $responseFormat);

        $this->assertEquals($requestParameters, $this->textSearchPlaceAdapter->getPlace()->getRequestParameters());

    }

}